package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DestinoLixo generated by hbm2java
 */
@Entity
@Table(name = "destino_lixo", catalog = "agentemaps")
public class DestinoLixo implements java.io.Serializable {

	private int familiaId;
	private Familia familia;
	private Byte coletado;
	private Byte queimadoEnterrado;
	private Byte ceuAberto;

	public DestinoLixo() {
	}

	public DestinoLixo(Familia familia) {
		this.familia = familia;
	}

	public DestinoLixo(Familia familia, Byte coletado, Byte queimadoEnterrado, Byte ceuAberto) {
		this.familia = familia;
		this.coletado = coletado;
		this.queimadoEnterrado = queimadoEnterrado;
		this.ceuAberto = ceuAberto;
	}

	@GenericGenerator(name = "fk_destino_lixo_familia", strategy = "foreign", parameters = @Parameter(name = "property", value = "familia"))
	@Id
	@GeneratedValue(generator = "fk_destino_lixo_familia")

	@Column(name = "familia_id", unique = true, nullable = false)
	public int getFamiliaId() {
		return this.familiaId;
	}

	public void setFamiliaId(int familiaId) {
		this.familiaId = familiaId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	@Column(name = "coletado")
	public Byte getColetado() {
		return this.coletado;
	}

	public void setColetado(Byte coletado) {
		this.coletado = coletado;
	}

	@Column(name = "queimado_enterrado")
	public Byte getQueimadoEnterrado() {
		return this.queimadoEnterrado;
	}

	public void setQueimadoEnterrado(Byte queimadoEnterrado) {
		this.queimadoEnterrado = queimadoEnterrado;
	}

	@Column(name = "ceu_aberto")
	public Byte getCeuAberto() {
		return this.ceuAberto;
	}

	public void setCeuAberto(Byte ceuAberto) {
		this.ceuAberto = ceuAberto;
	}

}
