package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Diabetico generated by hbm2java
 */
@Entity
@Table(name = "diabetico", catalog = "agentemaps")
public class Diabetico implements java.io.Serializable {

	private int membroId;
	private Membro membro;
	private Byte fazDieta;
	private Byte usaInsulina;
	private Byte tomaHipoglicemiante;
	private Byte dataUtilma;
	private Byte observacoes;
	private Byte fazExercicios;

	public Diabetico() {
	}

	public Diabetico(Membro membro) {
		this.membro = membro;
	}

	public Diabetico(Membro membro, Byte fazDieta, Byte usaInsulina, Byte tomaHipoglicemiante, Byte dataUtilma,
			Byte observacoes, Byte fazExercicios) {
		this.membro = membro;
		this.fazDieta = fazDieta;
		this.usaInsulina = usaInsulina;
		this.tomaHipoglicemiante = tomaHipoglicemiante;
		this.dataUtilma = dataUtilma;
		this.observacoes = observacoes;
		this.fazExercicios = fazExercicios;
	}

	@GenericGenerator(name = "fk_diabetico_membro", strategy = "foreign", parameters = @Parameter(name = "property", value = "membro"))
	@Id
	@GeneratedValue(generator = "fk_diabetico_membro")

	@Column(name = "membro_id", unique = true, nullable = false)
	public int getMembroId() {
		return this.membroId;
	}

	public void setMembroId(int membroId) {
		this.membroId = membroId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Membro getMembro() {
		return this.membro;
	}

	public void setMembro(Membro membro) {
		this.membro = membro;
	}

	@Column(name = "faz_dieta")
	public Byte getFazDieta() {
		return this.fazDieta;
	}

	public void setFazDieta(Byte fazDieta) {
		this.fazDieta = fazDieta;
	}

	@Column(name = "usa_insulina")
	public Byte getUsaInsulina() {
		return this.usaInsulina;
	}

	public void setUsaInsulina(Byte usaInsulina) {
		this.usaInsulina = usaInsulina;
	}

	@Column(name = "toma_hipoglicemiante")
	public Byte getTomaHipoglicemiante() {
		return this.tomaHipoglicemiante;
	}

	public void setTomaHipoglicemiante(Byte tomaHipoglicemiante) {
		this.tomaHipoglicemiante = tomaHipoglicemiante;
	}

	@Column(name = "data_utilma")
	public Byte getDataUtilma() {
		return this.dataUtilma;
	}

	public void setDataUtilma(Byte dataUtilma) {
		this.dataUtilma = dataUtilma;
	}

	@Column(name = "observacoes")
	public Byte getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(Byte observacoes) {
		this.observacoes = observacoes;
	}

	@Column(name = "faz_exercicios")
	public Byte getFazExercicios() {
		return this.fazExercicios;
	}

	public void setFazExercicios(Byte fazExercicios) {
		this.fazExercicios = fazExercicios;
	}

}
