package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FatoresRisco generated by hbm2java
 */
@Entity
@Table(name = "fatores_risco", catalog = "agentemaps")
public class FatoresRisco implements java.io.Serializable {

	private int gestanteId;
	private Gestante gestante;
	private Byte seisMaisGestacoes;
	private Byte natimortoAborto;
	private Byte trintaseisMais;
	private Byte menosVinte;
	private Byte sangramento;
	private Byte edema;
	private Byte diabetes;
	private Byte pressaoAlta;

	public FatoresRisco() {
	}

	public FatoresRisco(Gestante gestante) {
		this.gestante = gestante;
	}

	public FatoresRisco(Gestante gestante, Byte seisMaisGestacoes, Byte natimortoAborto, Byte trintaseisMais,
			Byte menosVinte, Byte sangramento, Byte edema, Byte diabetes, Byte pressaoAlta) {
		this.gestante = gestante;
		this.seisMaisGestacoes = seisMaisGestacoes;
		this.natimortoAborto = natimortoAborto;
		this.trintaseisMais = trintaseisMais;
		this.menosVinte = menosVinte;
		this.sangramento = sangramento;
		this.edema = edema;
		this.diabetes = diabetes;
		this.pressaoAlta = pressaoAlta;
	}

	@GenericGenerator(name = "fk_fatores_risco_gestante", strategy = "foreign", parameters = @Parameter(name = "property", value = "gestante"))
	@Id
	@GeneratedValue(generator = "fk_fatores_risco_gestante")

	@Column(name = "gestante_id", unique = true, nullable = false)
	public int getGestanteId() {
		return this.gestanteId;
	}

	public void setGestanteId(int gestanteId) {
		this.gestanteId = gestanteId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Gestante getGestante() {
		return this.gestante;
	}

	public void setGestante(Gestante gestante) {
		this.gestante = gestante;
	}

	@Column(name = "seis_mais_gestacoes")
	public Byte getSeisMaisGestacoes() {
		return this.seisMaisGestacoes;
	}

	public void setSeisMaisGestacoes(Byte seisMaisGestacoes) {
		this.seisMaisGestacoes = seisMaisGestacoes;
	}

	@Column(name = "natimorto_aborto")
	public Byte getNatimortoAborto() {
		return this.natimortoAborto;
	}

	public void setNatimortoAborto(Byte natimortoAborto) {
		this.natimortoAborto = natimortoAborto;
	}

	@Column(name = "trintaseis_mais")
	public Byte getTrintaseisMais() {
		return this.trintaseisMais;
	}

	public void setTrintaseisMais(Byte trintaseisMais) {
		this.trintaseisMais = trintaseisMais;
	}

	@Column(name = "menos_vinte")
	public Byte getMenosVinte() {
		return this.menosVinte;
	}

	public void setMenosVinte(Byte menosVinte) {
		this.menosVinte = menosVinte;
	}

	@Column(name = "sangramento")
	public Byte getSangramento() {
		return this.sangramento;
	}

	public void setSangramento(Byte sangramento) {
		this.sangramento = sangramento;
	}

	@Column(name = "edema")
	public Byte getEdema() {
		return this.edema;
	}

	public void setEdema(Byte edema) {
		this.edema = edema;
	}

	@Column(name = "diabetes")
	public Byte getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(Byte diabetes) {
		this.diabetes = diabetes;
	}

	@Column(name = "pressao_alta")
	public Byte getPressaoAlta() {
		return this.pressaoAlta;
	}

	public void setPressaoAlta(Byte pressaoAlta) {
		this.pressaoAlta = pressaoAlta;
	}

}
