package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Gestante generated by hbm2java
 */
@Entity
@Table(name = "gestante", catalog = "agentemaps")
public class Gestante implements java.io.Serializable {

	private int membroId;
	private Membro membro;
	private Date dataUltimo;
	private Date dataProvavel;
	private Date dataVacina;
	private Date dataPrenatal;
	private Integer fatoresRiscoId;
	private Integer agenteId;
	private FatoresRisco fatoresRisco;

	public Gestante() {
	}

	public Gestante(Membro membro) {
		this.membro = membro;
	}

	public Gestante(Membro membro, Date dataUltimo, Date dataProvavel, Date dataVacina, Date dataPrenatal,
			Integer fatoresRiscoId, Integer agenteId, FatoresRisco fatoresRisco) {
		this.membro = membro;
		this.dataUltimo = dataUltimo;
		this.dataProvavel = dataProvavel;
		this.dataVacina = dataVacina;
		this.dataPrenatal = dataPrenatal;
		this.fatoresRiscoId = fatoresRiscoId;
		this.agenteId = agenteId;
		this.fatoresRisco = fatoresRisco;
	}

	@GenericGenerator(name = "fk_gestante_membro", strategy = "foreign", parameters = @Parameter(name = "property", value = "membro"))
	@Id
	@GeneratedValue(generator = "fk_gestante_membro")

	@Column(name = "membro_id", unique = true, nullable = false)
	public int getMembroId() {
		return this.membroId;
	}

	public void setMembroId(int membroId) {
		this.membroId = membroId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Membro getMembro() {
		return this.membro;
	}

	public void setMembro(Membro membro) {
		this.membro = membro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_ultimo", length = 10)
	public Date getDataUltimo() {
		return this.dataUltimo;
	}

	public void setDataUltimo(Date dataUltimo) {
		this.dataUltimo = dataUltimo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_provavel", length = 10)
	public Date getDataProvavel() {
		return this.dataProvavel;
	}

	public void setDataProvavel(Date dataProvavel) {
		this.dataProvavel = dataProvavel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_vacina", length = 10)
	public Date getDataVacina() {
		return this.dataVacina;
	}

	public void setDataVacina(Date dataVacina) {
		this.dataVacina = dataVacina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_prenatal", length = 10)
	public Date getDataPrenatal() {
		return this.dataPrenatal;
	}

	public void setDataPrenatal(Date dataPrenatal) {
		this.dataPrenatal = dataPrenatal;
	}

	@Column(name = "fatores_risco_id")
	public Integer getFatoresRiscoId() {
		return this.fatoresRiscoId;
	}

	public void setFatoresRiscoId(Integer fatoresRiscoId) {
		this.fatoresRiscoId = fatoresRiscoId;
	}

	@Column(name = "agente_id")
	public Integer getAgenteId() {
		return this.agenteId;
	}

	public void setAgenteId(Integer agenteId) {
		this.agenteId = agenteId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "gestante")
	public FatoresRisco getFatoresRisco() {
		return this.fatoresRisco;
	}

	public void setFatoresRisco(FatoresRisco fatoresRisco) {
		this.fatoresRisco = fatoresRisco;
	}

}
