package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Hipertenso generated by hbm2java
 */
@Entity
@Table(name = "hipertenso", catalog = "agentemaps")
public class Hipertenso implements java.io.Serializable {

	private int membroId;
	private Membro membro;
	private Byte fumante;
	private Byte fazDieta;
	private Byte tomaMedicacao;
	private Byte fazExercicio;
	private Byte pressaoArterial;
	private Date dataUltima;
	private String observacoes;

	public Hipertenso() {
	}

	public Hipertenso(Membro membro) {
		this.membro = membro;
	}

	public Hipertenso(Membro membro, Byte fumante, Byte fazDieta, Byte tomaMedicacao, Byte fazExercicio,
			Byte pressaoArterial, Date dataUltima, String observacoes) {
		this.membro = membro;
		this.fumante = fumante;
		this.fazDieta = fazDieta;
		this.tomaMedicacao = tomaMedicacao;
		this.fazExercicio = fazExercicio;
		this.pressaoArterial = pressaoArterial;
		this.dataUltima = dataUltima;
		this.observacoes = observacoes;
	}

	@GenericGenerator(name = "fk_hipertenso_membro", strategy = "foreign", parameters = @Parameter(name = "property", value = "membro"))
	@Id
	@GeneratedValue(generator = "fk_hipertenso_membro")

	@Column(name = "membro_id", unique = true, nullable = false)
	public int getMembroId() {
		return this.membroId;
	}

	public void setMembroId(int membroId) {
		this.membroId = membroId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Membro getMembro() {
		return this.membro;
	}

	public void setMembro(Membro membro) {
		this.membro = membro;
	}

	@Column(name = "fumante")
	public Byte getFumante() {
		return this.fumante;
	}

	public void setFumante(Byte fumante) {
		this.fumante = fumante;
	}

	@Column(name = "faz_dieta")
	public Byte getFazDieta() {
		return this.fazDieta;
	}

	public void setFazDieta(Byte fazDieta) {
		this.fazDieta = fazDieta;
	}

	@Column(name = "toma_medicacao")
	public Byte getTomaMedicacao() {
		return this.tomaMedicacao;
	}

	public void setTomaMedicacao(Byte tomaMedicacao) {
		this.tomaMedicacao = tomaMedicacao;
	}

	@Column(name = "faz_exercicio")
	public Byte getFazExercicio() {
		return this.fazExercicio;
	}

	public void setFazExercicio(Byte fazExercicio) {
		this.fazExercicio = fazExercicio;
	}

	@Column(name = "pressao_arterial")
	public Byte getPressaoArterial() {
		return this.pressaoArterial;
	}

	public void setPressaoArterial(Byte pressaoArterial) {
		this.pressaoArterial = pressaoArterial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_ultima", length = 10)
	public Date getDataUltima() {
		return this.dataUltima;
	}

	public void setDataUltima(Date dataUltima) {
		this.dataUltima = dataUltima;
	}

	@Column(name = "observacoes", length = 65535)
	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

}
