package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membro generated by hbm2java
 */
@Entity
@Table(name = "membro", catalog = "agentemaps")
public class Membro implements java.io.Serializable {

	private Integer id;
	private int familiaId;
	private String cpf;
	private String nome;
	private Date dataNascimento;
	private int idade;
	private String sexo;
	private String escolaridade;
	private String ocupacao;
	private String condicoesSaude;
	private Diabetico diabetico;
	private Gestante gestante;
	private Hipertenso hipertenso;

	public Membro() {
	}

	public Membro(int familiaId, String nome, int idade, String sexo, String ocupacao, String condicoesSaude) {
		this.familiaId = familiaId;
		this.nome = nome;
		this.idade = idade;
		this.sexo = sexo;
		this.ocupacao = ocupacao;
		this.condicoesSaude = condicoesSaude;
	}

	public Membro(int familiaId, String cpf, String nome, Date dataNascimento, int idade, String sexo,
			String escolaridade, String ocupacao, String condicoesSaude, Diabetico diabetico, Gestante gestante,
			Hipertenso hipertenso) {
		this.familiaId = familiaId;
		this.cpf = cpf;
		this.nome = nome;
		this.dataNascimento = dataNascimento;
		this.idade = idade;
		this.sexo = sexo;
		this.escolaridade = escolaridade;
		this.ocupacao = ocupacao;
		this.condicoesSaude = condicoesSaude;
		this.diabetico = diabetico;
		this.gestante = gestante;
		this.hipertenso = hipertenso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "familia_id", nullable = false)
	public int getFamiliaId() {
		return this.familiaId;
	}

	public void setFamiliaId(int familiaId) {
		this.familiaId = familiaId;
	}

	@Column(name = "cpf", length = 16)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 10)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "idade", nullable = false)
	public int getIdade() {
		return this.idade;
	}

	public void setIdade(int idade) {
		this.idade = idade;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "escolaridade")
	public String getEscolaridade() {
		return this.escolaridade;
	}

	public void setEscolaridade(String escolaridade) {
		this.escolaridade = escolaridade;
	}

	@Column(name = "ocupacao", nullable = false)
	public String getOcupacao() {
		return this.ocupacao;
	}

	public void setOcupacao(String ocupacao) {
		this.ocupacao = ocupacao;
	}

	@Column(name = "condicoes_saude", nullable = false)
	public String getCondicoesSaude() {
		return this.condicoesSaude;
	}

	public void setCondicoesSaude(String condicoesSaude) {
		this.condicoesSaude = condicoesSaude;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "membro")
	public Diabetico getDiabetico() {
		return this.diabetico;
	}

	public void setDiabetico(Diabetico diabetico) {
		this.diabetico = diabetico;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "membro")
	public Gestante getGestante() {
		return this.gestante;
	}

	public void setGestante(Gestante gestante) {
		this.gestante = gestante;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "membro")
	public Hipertenso getHipertenso() {
		return this.hipertenso;
	}

	public void setHipertenso(Hipertenso hipertenso) {
		this.hipertenso = hipertenso;
	}

}
