package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TipoCasa generated by hbm2java
 */
@Entity
@Table(name = "tipo_casa", catalog = "agentemaps")
public class TipoCasa implements java.io.Serializable {

	private int familiaId;
	private Familia familia;
	private Byte tijoloAdobe;
	private Byte taipaRevestida;
	private Byte taipaNaoRevistida;
	private Byte mandeira;
	private Byte materialAproveitado;
	private String outroEspecificar;
	private Byte numeroComodo;
	private Byte energiaEletrica;

	public TipoCasa() {
	}

	public TipoCasa(Familia familia) {
		this.familia = familia;
	}

	public TipoCasa(Familia familia, Byte tijoloAdobe, Byte taipaRevestida, Byte taipaNaoRevistida, Byte mandeira,
			Byte materialAproveitado, String outroEspecificar, Byte numeroComodo, Byte energiaEletrica) {
		this.familia = familia;
		this.tijoloAdobe = tijoloAdobe;
		this.taipaRevestida = taipaRevestida;
		this.taipaNaoRevistida = taipaNaoRevistida;
		this.mandeira = mandeira;
		this.materialAproveitado = materialAproveitado;
		this.outroEspecificar = outroEspecificar;
		this.numeroComodo = numeroComodo;
		this.energiaEletrica = energiaEletrica;
	}

	@GenericGenerator(name = "fk_tipo_casa_familia", strategy = "foreign", parameters = @Parameter(name = "property", value = "familia"))
	@Id
	@GeneratedValue(generator = "fk_tipo_casa_familia")

	@Column(name = "familia_id", unique = true, nullable = false)
	public int getFamiliaId() {
		return this.familiaId;
	}

	public void setFamiliaId(int familiaId) {
		this.familiaId = familiaId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	@Column(name = "tijolo_adobe")
	public Byte getTijoloAdobe() {
		return this.tijoloAdobe;
	}

	public void setTijoloAdobe(Byte tijoloAdobe) {
		this.tijoloAdobe = tijoloAdobe;
	}

	@Column(name = "taipa_revestida")
	public Byte getTaipaRevestida() {
		return this.taipaRevestida;
	}

	public void setTaipaRevestida(Byte taipaRevestida) {
		this.taipaRevestida = taipaRevestida;
	}

	@Column(name = "taipa_nao_revistida")
	public Byte getTaipaNaoRevistida() {
		return this.taipaNaoRevistida;
	}

	public void setTaipaNaoRevistida(Byte taipaNaoRevistida) {
		this.taipaNaoRevistida = taipaNaoRevistida;
	}

	@Column(name = "mandeira")
	public Byte getMandeira() {
		return this.mandeira;
	}

	public void setMandeira(Byte mandeira) {
		this.mandeira = mandeira;
	}

	@Column(name = "material_aproveitado")
	public Byte getMaterialAproveitado() {
		return this.materialAproveitado;
	}

	public void setMaterialAproveitado(Byte materialAproveitado) {
		this.materialAproveitado = materialAproveitado;
	}

	@Column(name = "outro_especificar")
	public String getOutroEspecificar() {
		return this.outroEspecificar;
	}

	public void setOutroEspecificar(String outroEspecificar) {
		this.outroEspecificar = outroEspecificar;
	}

	@Column(name = "numero_comodo")
	public Byte getNumeroComodo() {
		return this.numeroComodo;
	}

	public void setNumeroComodo(Byte numeroComodo) {
		this.numeroComodo = numeroComodo;
	}

	@Column(name = "energia_eletrica")
	public Byte getEnergiaEletrica() {
		return this.energiaEletrica;
	}

	public void setEnergiaEletrica(Byte energiaEletrica) {
		this.energiaEletrica = energiaEletrica;
	}

}
