package br.com.agentemaps.model;
// Generated 26/09/2016 16:25:14 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TratamentoAgua generated by hbm2java
 */
@Entity
@Table(name = "tratamento_agua", catalog = "agentemaps")
public class TratamentoAgua implements java.io.Serializable {

	private int familiaId;
	private Familia familia;
	private Byte filtracao;
	private Byte fervura;
	private Byte cloracao;
	private Byte semTratamento;

	public TratamentoAgua() {
	}

	public TratamentoAgua(Familia familia) {
		this.familia = familia;
	}

	public TratamentoAgua(Familia familia, Byte filtracao, Byte fervura, Byte cloracao, Byte semTratamento) {
		this.familia = familia;
		this.filtracao = filtracao;
		this.fervura = fervura;
		this.cloracao = cloracao;
		this.semTratamento = semTratamento;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "familia"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "familia_id", unique = true, nullable = false)
	public int getFamiliaId() {
		return this.familiaId;
	}

	public void setFamiliaId(int familiaId) {
		this.familiaId = familiaId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Familia getFamilia() {
		return this.familia;
	}

	public void setFamilia(Familia familia) {
		this.familia = familia;
	}

	@Column(name = "filtracao")
	public Byte getFiltracao() {
		return this.filtracao;
	}

	public void setFiltracao(Byte filtracao) {
		this.filtracao = filtracao;
	}

	@Column(name = "fervura")
	public Byte getFervura() {
		return this.fervura;
	}

	public void setFervura(Byte fervura) {
		this.fervura = fervura;
	}

	@Column(name = "cloracao")
	public Byte getCloracao() {
		return this.cloracao;
	}

	public void setCloracao(Byte cloracao) {
		this.cloracao = cloracao;
	}

	@Column(name = "sem_tratamento")
	public Byte getSemTratamento() {
		return this.semTratamento;
	}

	public void setSemTratamento(Byte semTratamento) {
		this.semTratamento = semTratamento;
	}

}
